#!/bin/sh

VERSION="1.0+20151101"

help() { cat <</help
Usage: isosuck [DVD Title] [DVD DEVICE]

DVD Title will default to the DVD's internal volume ID
Output will be <DVD Title>.iso
DVD DEVICE will default to /dev/dvd

isosuck $VERSION Copyright 2010+ Adam Katz <www.khopis.com/scripts>, GPLv2
Learn more at https://github.com/adamhotep/media-scripts
/help
exit
}

version() { cat <</version
isosuck $VERSION
Copyright (C) 2010+  Adam Katz
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
/version
exit
}

license() { cat <</license
Copyright (C) 2010+  Adam Katz

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
/license
exit
}

# silently returns true only when we have all of the given command(s)
we_have() { command -v "$@" >/dev/null 2>&1; }

# print the arguments and exit the entire program
die() { echo "$*" >&2; exit 2; }

while getopts hV-: arg; do
  case "$arg" in
    (h) help ;;
    (V) version ;;
    (L) license ;;
    (-) case "$OPTARG" in
          (help)	help ;;
          (license)	license ;;
          (version)	version ;;
          (*)		die "Illegal option --$OPTARG ... Try --help" ;;
        esac ;;
    (\?) die "Try --help" ;;
  esac
done
shift $((OPTIND-1))

if [ "$1" != "${1#-}" ]; then
  help
  if [ "$1" = -h -o "$1" = --help ]; then exit 0; fi
  exit 2
fi

if ! we_have isoinfo; then
  echo "This program requires isoinfo; try installing genisoimage or cdrkit" >&2
  exit 2
fi

TITLE="$1"

for DEVICE in "$2" "/dev/dvd" "/dev/sr0" "/dev/sr1" "/dev/sr2" "/dev/sr3"; do
  if [ -b "$DEVICE" ]; then
    break
  fi
done

if [ ! -b "$DEVICE" ]; then
  echo "ERROR: Could not find an appropriate DVD device." >&2
  exit 2
elif [ -n "$2" ] && [ "$2" != "$DEVICE" ]; then
  echo "WARNING: '$2' is not a block device, using '$DEVICE' instead." >&2
  sleep 1
fi

dvdinfo() { isoinfo -d -i "$DEVICE" 2>/dev/null; }

if we_have dc3dd; then
  image() { dc3dd hash=md5 if="$DEVICE" of="$1"; }
else
  if we_have md5sum; then # GNU
    hash() { md5sum "$1" |awk '{print $1}'; }
  elif we_have md5; then # BSD
    hash() { md5 "$1" |awk '{print $NF}'; }
  elif we_have cksum; then # old POSIX (use sum and size)
    hash() { cksum "$1" |awk '{print $1,$2}'; }
  else  # wtf, no cksum?!  use just size
    hash() { /bin/ls -l "$1" |awk '{print $5}'; }
  fi
  image() {
    local RETVAL orig new
    dd if="$DEVICE" of="$1"
    RETVAL=$?
    if [ $RETVAL != 0 ]; then
      echo "WARNING: dd did not exit cleanly (code $RETVAL)" >&2
      echo "         (performing hash check anyway, may be a waste of time)" >&2
    fi
    orig=`hash "$DEVICE"`
    new=`hash "$1"`
    if [ "$orig" != "$new" ]; then
      echo "FAILURE: Hash mismatch on output '$1'" >&2
      return 1
    else
      echo "Success: Hash matches original source."
    fi
    return $RETVAL
  }
fi

DEFAULT_TITLE=DVD_VIDEO

if [ -z "$TITLE" ]; then
  TITLE=`dvdinfo |sed '/^Volume id: /!d; s///'`
fi
if [ -z "$TITLE" ]; then
  TITLE=DVD_VIDEO
fi
if [ "$TITLE" = "$DEFAULT_TITLE" ]; then
  i=1
  while [ -s "$TITLE.iso" ]; do
    TITLE="$BASE-$i"
    i=$((i+1))
  done
fi

if [ -s "$TITLE.iso" ]; then
  echo "Output '$TITLE.iso' already exists, aborting." >&2
  exit 1
fi

# BSD readlink doesn't support GNU readlink's -f/--canonicalize
if ! readlink --help 2>&1 |grep -l .--canonicalize >/dev/null; then
  readlink() {
    if [ "$1" = "--canonicalize" ]; then
      shift
    fi
    if [ ! -h "$1" ]; then
      echo "$1"
      return
    fi
    #next=`ls -l "$1" |sed 's/.* -> //'`
    next=`builtin readlink "$1"`
    readlink "$next"
  }
fi

TRUE_DEVICE=`readlink --canonicalize "$DEVICE" 2>/dev/null || echo "$DEVICE"`
MOUNTED=`mount |awk -v dvd="$TRUE_DEVICE" '$1 == dvd'`
MOUNTED="${MOUNTED#* on /}"
MOUNTED="${MOUNTED%% *}"
OLDTITLE="${MOUNTED##*/}"
if [ -n "$MOUNTED" ] && [ "$MOUNTED" = "${MOUNTED%*/$TITLE}" ]; then
  MOUNTED="/$MOUNTED"
  echo "WARNING: You appear to have a different DVD ($OLDTITLE) mounted."
  echo "         This could result in the output being truncated."
  echo "         I'll UNMOUNT '$MOUNTED' in five seconds.  You've been warned."
  sleep 5
  umount "$MOUNTED"
fi

LOCATION=`dirname "$TITLE.iso"`
FREE=`df -k "$LOCATION" |awk 'NR==2 && $4 { print $4 }'`

SIZE=`dvdinfo |awk '
  /^Logical block size is:/ { block = $NF }
  /^Volume size is:/ { vol = $NF }
  END {
    size = sprintf("%.0f", block * vol / 1024)
    min = 4 * 1024^2   # a minimum size in case isoinfo fails
    printf "%.0f", (size > min ? size : min)
  }
'`

echo "$TITLE^$SIZE^$DEVICE" |awk -F ^ '{
  printf "Will write `%s.iso` (%.2fG) from `%s`",
         $1, $(NF-1) / 1024 / 1024, $NF
}'
sleep 2

# warn if we'd have less than 1GB free after ripping
if [ $SIZE -ge $((FREE-1024*1024)) ]; then
  echo |awk -v SIZE="$SIZE" -v FREE="$FREE" '{
    printf "WARNING: Disk image is %.2fG but we only have %.2fG free space\n",
      SIZE / 1024^2, FREE / 1024^2
  }' >&2
  echo "... waiting 20 seconds for you to cancel"
  sleep 20
  echo
fi

if [ "${TERM:-no_term}" = "${TERM#[Ll]inux}" ]; then
  printf "\033]0;${0##*/}: $TITLE\a"
fi

image "$TITLE.iso"
RETVAL=$?

ACTUAL_SIZE=`du -k "$TITLE.iso" |awk '{print $1}'`

# if actual size is 5+ MB smaller than expected size
if [ "$ACTUAL_SIZE" -lt "$((SIZE-5*1024))" ]; then
  echo "$ACTUAL_SIZE $SIZE" |awk '{
    printf "WARNING: final size (%.2fG) is %.1fM smaller than expected (%.2fG)",
      $1 / 1024 / 1024, ($2 - $1) / 1024, $2 / 1024 / 1024;
  }' >&2
  exit 2
fi

exit $RETVAL
