#!/bin/sh
help() { cat <</help
Usage: kodi-command [OPTIONS] COMMAND|JSON
   or: kodi-command [OPTIONS] METHOD [PARAM]

Options:
  -c FILE  Configuration file (default: \`$api_creds\`)
           For further info, run \`${0##*/} --config-help\`
  -q       Make output quieter, -qq also suppresses response JSON
  -u URL   The kodi control URL (default: \`url\` value from config file)

Command aliases:
  clean, clean-audio    Clean library: VideoLibrary.Clean or AudioLibrary.Clean
  info                  Get info on the video or audio being played
  mute                  Toggle mute: Application.SetMute
  open FILE             Open and play FILE
  play, pause           Toggle between play and pause (video)
  quit                  Exit kodi
  update, update-audio  Update library: VideoLibrary.Scan or AudioLibrary.Scan

This requires you to have enabled the web server
  Settings -> Services -> Control -> Allow remote control via HTTP
Docs for JSON, methods, and parameters: $api_link

A part of media-scripts, https://github.com/adamhotep/media-scripts
kodi-remote 0.2.20230423.1 copyright 2021+ by Adam Katz, GPLv2+
/help
  exit
}

# Output a warning text to standard error and optionally exit
# Usage: warn [-x] [MESSAGE]
warn() {
  if [ "$1" = -x ]; then die=2; shift; fi
  echo "$*" >&2
  if [ "$die" -ge 0 ]; then exit $die; fi
}

api_file_help() { cat <</api_help
\`$api_creds\` is a curl config file,
called with \`curl --config FILE\` (see \`man curl\`).

It should look like this (with no indentation, ideally with a better password):

    url = "http://localhost:8080/jsonrpc"
    user = "kodi_user:kodi_webapi_PA55w0rd"

That's a plain-text password in an unencrypted file, which is not at all ideal!
Please at least use file mode 600 (-rw-------) or 400 (-r--------)
/api_help
  exit $1
}

# constants
api_link="https://kodi.wiki/view/JSON-RPC_API/v13"
qq='"'

# defaults
api_creds="$HOME/.kodi/.api_creds"
url=
quiet=0

# load options
needs_arg() {
  if [ -z "$OPTARG" ]; then
    warn -x "No arg for --$OPT option"
  fi
}
while getopts c:hqu:v-: OPT; do
  if [ "$OPT" = - ]; then # long opt https://stackoverflow.com/a/28466267/519360
    OPT="${OPTARG%%=*}" OPTARG="${OPTARG#$OPT}" OPTARG="${OPTARG#=}"
  fi
  case $OPT in
    ( c* )  if [ -z "$OPTARG" ]; then api_file_help; fi; api_creds="$OPTARG" ;;
    ( h* )  help ;;
    ( q* )  quiet=$(( quiet + 1 )) ;;
    ( u* )  needs_arg; url="$OPTARG" ;;
    ( v* )  quiet=$(( quiet - 1 )) ;;
    ( ??* ) warn "Illegal option --$OPT"; warn -x "Try \`${0##*/} --help\`" ;;
    ( ?  )  warn -x "Try \`${0##*/} --help\`" ;;
  esac
done
shift $((OPTIND-1))

if ! [ -s "$api_creds" ] || ! [ -r "$api_creds" ]; then
  warn "You don't have a nonzero-sized readable '$api_creds' file."
  api_file_help 2
fi

# Run a Kodi JSON command
# Usage: kodi_json_cmd JSON
kodi_json_cmd() {
  case $quiet in
    ( 0 | -* ) silent='' ;;
    ( 1 ) silent='--silent' ;;
    ( * ) silent='--silent --output /dev/null' ;;
  esac
  curl --config "$api_creds" $silent --request POST \
    --header "content-type:application/json" --data "$*" ${url:+"$url"}
}

# Run a basic command (an alias or a method with optional parameter(s)
# Usage: kodi_cmd COMMAND [PARAM...]
kodi_cmd() {
  method="$1" params=
  shift
  case "$*" in
    ( \{*\} )	params='"params":'"$*" ;;
    ( * )
      params='"params":{'
      key=1
      comma=
      for p in "$@"; do
        if [ $key = 1 ]; then
          params="$params$comma$qq$p$qq:"
          comma=','
          key=0
        elif [ "$p" = "${p#*[^0-9]}" ] || [ "$p" != "${p#\[}" ]; then
          # pure numeric value or a JSON nested structure, take as-is (no quotes)
          params="$params$p"
          key=1
        else
          params="$params$qq$p$qq"
          key=1
        fi
      done
      params="$params}"
      ;;
  esac
  # Run constructed JSON with identifier set to identify this script and its PID
  kodi_json_cmd "$(printf \
    '{ "jsonrpc": "2.0", "id": "kodi-command[%d]", "method": "%s", %s }' \
    "$$" "$method" "$params"
  )"
}

kodi_info() {
  # Why does this need to be more quiet than other curl commands?
  case "$(quiet=$((quiet+1)) kodi_cmd Player.GetActivePlayers)" in
    ( *'"type":"video"'* ) kodi_json_cmd '{
        "jsonrpc": "2.0",
        "method": "Player.GetItem",
        "params": {
          "properties": [
            "title", "album", "artist", "season", "episode", "duration",
            "showtitle", "tvshowid", "file"
          ],
          "playerid": 1
        },
      "id": "VideoGetItem"
    }' ;;
    ( *'"type":"audio"'* ) kodi_json_cmd '{
        "jsonrpc": "2.0",
        "method": "Player.GetItem",
        "params": {
          "properties": [ "title", "album", "artist", "duration", "file" ],
          "playerid": 0
        },
        "id": "AudioGetItem"
      }' ;;
  esac
}

# Convert relative paths to absolute paths
# Usage: realpath PATH
if ! command -v realpath >/dev/null; then
  realpath() { readlink -f "$@"; }
fi

# Play a file or toggle play/pause on a given playerid (default=1, video)
kodi_play() {
  if [ "$*" -ge 0 ] 2>/dev/null; then	# non-negative number: toggle playerid
    kodi_cmd Player.PlayPause playerid "$1"
  elif [ -z "$1" ]; then		# no argument: toggle video
    kodi_cmd Player.PlayPause playerid 1
  else
    kodi_cmd Player.Open '{"item":{"file":"'"$(realpath "$1")"'"}}'
  fi
}


case "$1" in
  ( help )				help ;;

  # Aliases for common commands
  ( aplay | aplaypause | apause )	kodi_play 0 ;;
  ( clean | clean*vid* | clean*mov* )	kodi_cmd VideoLibrary.Clean ;;
  ( clean-audio* | clean*music* )	kodi_cmd AudioLibrary.Clean ;;
  ( info )				kodi_info ;;
  ( mute | unmute )			kodi_cmd Application.SetMute ;;
  ( open | play )			shift; kodi_play "$@" ;;
  ( play* | pause | vplay* | vpause )	kodi_play ;;
  ( stop )				kodi_cmd Player.Stop playerid ${2:-1} ;;
  ( quit | exit )			kodi_cmd Application.Quit ;;
  ( update | upd*vid* | upd*mov* )	kodi_cmd VideoLibrary.Scan ;;
  ( update-audio* | update*music* )	kodi_cmd AudioLibrary.Scan ;;

  ( \{* )	kodi_json_cmd "$*" ;;
  ( *.* )	kodi_cmd "$@" ;;
  ( * ) 	warn "Unknown command: '$*'"
  		warn -x "Try \`${0##*/} --help\`"
  		;;
esac
