#!/bin/bash
# Bash is used for arrays, mostly
help() { cat <</help
Mass convert given media FILEs to audio-only opus
Usage: ${0##*/} [OPTIONS] [CODEC [CODEC_OPTIONS]] FILE...

  --extension=STRING  Use this file extension string rather than \`$ext\`
  --noop, --test      Do nothing, just show what would have been done
  --prefix=DIRECTORY  Directory to prefix the FILE with

CODEC defaults to \`copy\`. Transcode with \`libopus\`
CODEC_OPTIONS are passed to FFMPEG after the \`-c:a CODEC\`

A part of media-scripts, https://github.com/adamhotep/media-scripts
media2opus 0.3.20240815.0 copyright 2021+ by Adam Katz <@adamhotep>, GPL
/help
  exit
}

declare -a args
target=''
ext='opus'
while [ $# -gt 0 ]; do
  if [ -f "$1" ]; then break; fi
  case $1 in
    ( -- )				break ;;
    ( --ext*=* )			ext="${1#*=}" ;;
    ( -extension | --ext* )		ext="$2"; shift ;;
    ( -noop | -test | --noop | --test )	noop=echo ;;
    ( -h | -help | --help )		help ;;
    ( --prefix=* )			prefix="${1#*=}" ;;
    ( -prefix | --prefix )		prefix="$2"; shift ;;
    ( * )				args+=($1) ;;
  esac
  shift
done

if [ -n "$prefix" ]; then
  prefix="${prefix%/}/"
  if ! [ -d "$prefix" ]; then
    read -p "Prefix directory '$prefix' doesn't exist. Create it [Yn]? " yn
    if [[ $yn == [Nn0]* ]]; then echo "Aborted."; exit; fi
    $noop mkdir -p "$prefix"
  fi
fi

if [[ ${#args[@]} == 0 ]]; then
  args=(copy)
fi

for f in "$@"; do
  out="$prefix${f%.*}.$ext"
  if [ -s "$f" ] && [ "$out" != "$f" ]; then
    # -map_metadata is new, from https://superuser.com/q/1235939/300293
    $noop ffmpeg -i "$f" -vn -map_metadata 0:s:a:0 -c:a "${args[@]}" "$out" \
      && $noop touch --reference="$f" "$out" >/dev/null 2>&1
  fi
done
